import type { Translations } from './types';

export enum Language {
  EN = 'en',
  ZH = 'zh',
  JA = 'ja',
  TA = 'ta',
  FR = 'fr',
  HI = 'hi',
  KN = 'kn',
  TE = 'te',
  ML = 'ml',
  AR = 'ar',
}

export const translations: { [key in Language]: Translations } = {
  [Language.EN]: {
    appName: 'PhishGuard AI',
    login: 'Login',
    signup: 'Sign Up',
    logout: 'Logout',
    emailAddress: 'Email Address',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    dontHaveAccount: "Don't have an account?",
    alreadyHaveAccount: 'Already have an account?',
    getStarted: 'Get Started',
    createAccount: 'Create Account',
    mainHeader: 'Phishing Email Detector',
    mainSubheader: 'Analyze email content for threats with the power of AI.',
    pasteEmail: 'Paste Email Content Below',
    pastePlaceholder: 'Paste the full email content here, including headers if possible...',
    or: 'OR',
    uploadFile: 'Upload an email file (.txt, .eml)',
    analyze: 'Analyze',
    analyzing: 'Analyzing...',
    analysisResult: 'Analysis Result',
    verdict: 'Verdict',
    reason: 'Reason',
    history: 'Analysis History',
    noHistory: 'No analyses yet. Start by analyzing an email above.',
    error: 'An Error Occurred',
    errorDescription: 'Could not analyze the email. The content might be too short or the API service is currently unavailable. Please try again later.',
    fileReadError: 'Failed to read the uploaded file. Please ensure it is a valid text file.',
  },
  [Language.ZH]: {
    appName: '钓鱼邮件卫士 AI',
    login: '登录',
    signup: '注册',
    logout: '登出',
    emailAddress: '电子邮件地址',
    password: '密码',
    confirmPassword: '确认密码',
    dontHaveAccount: '还没有账户？',
    alreadyHaveAccount: '已有账户？',
    getStarted: '开始使用',
    createAccount: '创建账户',
    mainHeader: '钓鱼邮件检测器',
    mainSubheader: '借助 AI 的力量分析电子邮件内容以发现威胁。',
    pasteEmail: '在下方粘贴电子邮件内容',
    pastePlaceholder: '在此处粘贴完整的电子邮件内容，如果可能，请包括标题...',
    or: '或',
    uploadFile: '上传电子邮件文件 (.txt, .eml)',
    analyze: '分析',
    analyzing: '分析中...',
    analysisResult: '分析结果',
    verdict: '结论',
    reason: '原因',
    history: '分析历史',
    noHistory: '尚无分析。从上方分析一封电子邮件开始。',
    error: '发生错误',
    errorDescription: '无法分析该电子邮件。内容可能太短或 API 服务当前不可用。请稍后再试。',
    fileReadError: '无法读取上传的文件。请确保它是一个有效的文本文件。',
  },
  [Language.JA]: {
    appName: 'フィッシュガード AI',
    login: 'ログイン',
    signup: 'サインアップ',
    logout: 'ログアウト',
    emailAddress: 'メールアドレス',
    password: 'パスワード',
    confirmPassword: 'パスワードを確認',
    dontHaveAccount: 'アカウントをお持ちでないですか？',
    alreadyHaveAccount: 'すでにアカウントをお持ちですか？',
    getStarted: '始める',
    createAccount: 'アカウントを作成',
    mainHeader: 'フィッシングメール検出器',
    mainSubheader: 'AI の力でメールの内容を分析し、脅威を検出します。',
    pasteEmail: '以下にメールの内容を貼り付け',
    pastePlaceholder: '可能であればヘッダーを含め、メールの全文をここに貼り付けてください...',
    or: 'または',
    uploadFile: 'メールファイルをアップロード (.txt, .eml)',
    analyze: '分析',
    analyzing: '分析中...',
    analysisResult: '分析結果',
    verdict: '判定',
    reason: '理由',
    history: '分析履歴',
    noHistory: 'まだ分析はありません。上でメールを分析することから始めてください。',
    error: 'エラーが発生しました',
    errorDescription: 'メールを分析できませんでした。内容が短すぎるか、API サービスが現在利用できない可能性があります。後でもう一度お試しください。',
    fileReadError: 'アップロードされたファイルを読み取れませんでした。有効なテキストファイルであることを確認してください。',
  },
  [Language.TA]: {
    appName: 'ஃபிஷ்கார்ட் AI',
    login: 'உள்நுழை',
    signup: 'பதிவுபெறுக',
    logout: 'வெளியேறு',
    emailAddress: 'மின்னஞ்சல் முகவரி',
    password: 'கடவுச்சொல்',
    confirmPassword: 'கடவுச்சொல்லை உறுதிப்படுத்தவும்',
    dontHaveAccount: 'கணக்கு இல்லையா?',
    alreadyHaveAccount: 'ஏற்கனவே கணக்கு உள்ளதா?',
    getStarted: 'தொடங்கவும்',
    createAccount: 'கணக்கை உருவாக்கு',
    mainHeader: 'ஃபிஷிங் மின்னஞ்சல் கண்டறிதல் கருவி',
    mainSubheader: 'AI இன் சக்தியுடன் அச்சுறுத்தல்களுக்கு மின்னஞ்சல் உள்ளடக்கத்தை பகுப்பாய்வு செய்யுங்கள்.',
    pasteEmail: 'மின்னஞ்சல் உள்ளடக்கத்தை கீழே ஒட்டவும்',
    pastePlaceholder: 'முழு மின்னஞ்சல் உள்ளடக்கத்தையும் இங்கே ஒட்டவும், முடிந்தால் தலைப்புகளையும் சேர்க்கவும்...',
    or: 'அல்லது',
    uploadFile: 'மின்னஞ்சல் கோப்பை பதிவேற்றவும் (.txt, .eml)',
    analyze: 'பகுப்பாய்வு செய்',
    analyzing: 'பகுப்பாய்வு செய்யப்படுகிறது...',
    analysisResult: 'பகுப்பாய்வு முடிவு',
    verdict: 'தீர்ப்பு',
    reason: 'காரணம்',
    history: 'பகுப்பாய்வு வரலாறு',
    noHistory: 'இன்னும் பகுப்பாய்வுகள் இல்லை. மேலே ஒரு மின்னஞ்சலை பகுப்பாய்வு செய்வதன் மூலம் தொடங்கவும்.',
    error: 'ஒரு பிழை ஏற்பட்டது',
    errorDescription: 'மின்னஞ்சலை பகுப்பாய்வு செய்ய முடியவில்லை. உள்ளடக்கம் மிகக் குறைவாக இருக்கலாம் அல்லது API சேவை தற்போது கிடைக்கவில்லை. தயவுசெய்து பின்னர் மீண்டும் முயற்சிக்கவும்.',
    fileReadError: 'பதிவேற்றிய கோப்பைப் படிக்கத் தவறிவிட்டது. இது ஒரு சரியான உரை கோப்பு என்பதை உறுதிப்படுத்தவும்.',
  },
  [Language.FR]: {
    appName: 'PhishGuard IA',
    login: 'Connexion',
    signup: "S'inscrire",
    logout: 'Déconnexion',
    emailAddress: 'Adresse e-mail',
    password: 'Mot de passe',
    confirmPassword: 'Confirmez le mot de passe',
    dontHaveAccount: 'Vous n’avez pas de compte ?',
    alreadyHaveAccount: 'Vous avez déjà un compte ?',
    getStarted: 'Commencer',
    createAccount: 'Créer un compte',
    mainHeader: 'Détecteur d’e-mails de phishing',
    mainSubheader: 'Analysez le contenu des e-mails à la recherche de menaces grâce à la puissance de l’IA.',
    pasteEmail: 'Collez le contenu de l’e-mail ci-dessous',
    pastePlaceholder: 'Collez ici le contenu complet de l’e-mail, y compris les en-têtes si possible...',
    or: 'OU',
    uploadFile: 'Télécharger un fichier e-mail (.txt, .eml)',
    analyze: 'Analyser',
    analyzing: 'Analyse en cours...',
    analysisResult: "Résultat de l'analyse",
    verdict: 'Verdict',
    reason: 'Raison',
    history: "Historique de l'analyse",
    noHistory: "Aucune analyse pour le moment. Commencez par analyser un e-mail ci-dessus.",
    error: 'Une erreur est survenue',
    errorDescription: 'Impossible d’analyser l’e-mail. Le contenu est peut-être trop court ou le service API est actuellement indisponible. Veuillez réessayer plus tard.',
    fileReadError: 'Échec de la lecture du fichier téléchargé. Veuillez vous assurer qu’il s’agit d’un fichier texte valide.',
  },
  [Language.HI]: {
    appName: 'फ़िशगार्ड एआई',
    login: 'लॉग इन करें',
    signup: 'साइन अप करें',
    logout: 'लॉग आउट',
    emailAddress: 'ईमेल पता',
    password: 'पासवर्ड',
    confirmPassword: 'पासवर्ड की पुष्टि कीजिये',
    dontHaveAccount: 'खाता नहीं है?',
    alreadyHaveAccount: 'पहले से ही खाता है?',
    getStarted: 'शुरू करें',
    createAccount: 'खाता बनाएं',
    mainHeader: 'फ़िशिंग ईमेल डिटेक्टर',
    mainSubheader: 'एआई की शक्ति से खतरों के लिए ईमेल सामग्री का विश्लेषण करें।',
    pasteEmail: 'नीचे ईमेल सामग्री पेस्ट करें',
    pastePlaceholder: 'यहां पूरी ईमेल सामग्री पेस्ट करें, यदि संभव हो तो हेडर सहित...',
    or: 'या',
    uploadFile: 'एक ईमेल फ़ाइल अपलोड करें (.txt, .eml)',
    analyze: 'विश्लेषण',
    analyzing: 'विश्लेषण हो रहा है...',
    analysisResult: 'विश्लेषण परिणाम',
    verdict: 'निर्णय',
    reason: 'कारण',
    history: 'विश्लेषण इतिहास',
    noHistory: 'अभी तक कोई विश्लेषण नहीं। ऊपर एक ईमेल का विश्लेषण करके प्रारंभ करें।',
    error: 'एक त्रुटि हुई',
    errorDescription: 'ईमेल का विश्लेषण नहीं किया जा सका। सामग्री बहुत छोटी हो सकती है या एपीआई सेवा वर्तमान में अनुपलब्ध है। कृपया बाद में पुन: प्रयास करें।',
    fileReadError: 'अपलोड की गई फ़ाइल को पढ़ने में विफल। कृपया सुनिश्चित करें कि यह एक मान्य पाठ फ़ाइल है।',
  },
  [Language.KN]: {
    appName: 'ಫಿಶ್‌ಗಾರ್ಡ್ AI',
    login: 'ಲಾಗಿನ್',
    signup: 'ಸೈನ್ ಅಪ್',
    logout: 'ಲಾಗ್ ಔಟ್',
    emailAddress: 'ಇಮೇಲ್ ವಿಳಾಸ',
    password: 'ಪಾಸ್ವರ್ಡ್',
    confirmPassword: 'ಪಾಸ್ವರ್ಡ್ ದೃಢೀಕರಿಸಿ',
    dontHaveAccount: 'ಖಾತೆ ಇಲ್ಲವೆ?',
    alreadyHaveAccount: 'ಈಗಾಗಲೇ ಖಾತೆ ಇದೆಯೆ?',
    getStarted: 'ಪ್ರಾರಂಭಿಸಿ',
    createAccount: 'ಖಾತೆ ತೆರೆಯಿರಿ',
    mainHeader: 'ಫಿಶಿಂಗ್ ಇಮೇಲ್ ಪತ್ತೆಕಾರಕ',
    mainSubheader: 'AI ಶಕ್ತಿಯೊಂದಿಗೆ ಬೆದರಿಕೆಗಳಿಗಾಗಿ ಇಮೇಲ್ ವಿಷಯವನ್ನು ವಿಶ್ಲೇಷಿಸಿ.',
    pasteEmail: 'ಕೆಳಗೆ ಇಮೇಲ್ ವಿಷಯವನ್ನು ಅಂಟಿಸಿ',
    pastePlaceholder: 'ಸಾಧ್ಯವಾದರೆ ಹೆಡರ್‌ಗಳನ್ನು ಒಳಗೊಂಡಂತೆ ಪೂರ್ಣ ಇಮೇಲ್ ವಿಷಯವನ್ನು ಇಲ್ಲಿ ಅಂಟಿಸಿ...',
    or: 'ಅಥವಾ',
    uploadFile: 'ಇಮೇಲ್ ಫೈಲ್ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ (.txt, .eml)',
    analyze: 'ವಿಶ್ಲೇಷಿಸಿ',
    analyzing: 'ವಿಶ್ಲೇಷಿಸಲಾಗುತ್ತಿದೆ...',
    analysisResult: 'ವಿಶ್ಲೇಷಣೆ ಫಲಿತಾಂಶ',
    verdict: 'ತೀರ್ಪು',
    reason: 'ಕಾರಣ',
    history: 'ವಿಶ್ಲೇಷಣೆ ಇತಿಹಾಸ',
    noHistory: 'ಇನ್ನೂ ಯಾವುದೇ ವಿಶ್ಲೇಷಣೆಗಳಿಲ್ಲ. ಮೇಲೆ ಇಮೇಲ್ ವಿಶ್ಲೇಷಿಸುವ ಮೂಲಕ ಪ್ರಾರಂಭಿಸಿ.',
    error: 'ದೋಷ ಸಂಭವಿಸಿದೆ',
    errorDescription: 'ಇಮೇಲ್ ವಿಶ್ಲೇಷಿಸಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ. ವಿಷಯವು ತುಂಬಾ ಚಿಕ್ಕದಾಗಿರಬಹುದು ಅಥವಾ API ಸೇವೆ ಪ್ರಸ್ತುತ ಲಭ್ಯವಿಲ್ಲ. ದಯವಿಟ್ಟು ನಂತರ ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.',
    fileReadError: 'ಅಪ್‌ಲೋಡ್ ಮಾಡಿದ ಫೈಲ್ ಓದಲು ವಿಫಲವಾಗಿದೆ. ದಯವಿಟ್ಟು ಇದು ಮಾನ್ಯ ಪಠ್ಯ ಫೈಲ್ ಎಂದು ಖಚಿತಪಡಿಸಿಕೊಳ್ಳಿ.',
  },
  [Language.TE]: {
    appName: 'ఫిష్‌గార్డ్ AI',
    login: 'లాగిన్',
    signup: 'సైన్ అప్',
    logout: 'లాగ్ అవుట్',
    emailAddress: 'ఇమెయిల్ చిరునామా',
    password: 'పాస్వర్డ్',
    confirmPassword: 'పాస్వర్డ్ను నిర్ధారించండి',
    dontHaveAccount: 'ఖాతా లేదా?',
    alreadyHaveAccount: 'ఇప్పటికే ఖాతా ఉందా?',
    getStarted: 'ప్రారంభించండి',
    createAccount: 'ఖాతాను సృష్టించండి',
    mainHeader: 'ఫిషింగ్ ఇమెయిల్ డిటెక్టర్',
    mainSubheader: 'AI శక్తితో బెదిరింపుల కోసం ఇమెయిల్ కంటెంట్‌ను విశ్లేషించండి.',
    pasteEmail: 'దిగువ ఇమెయిల్ కంటెంట్‌ను అతికించండి',
    pastePlaceholder: 'సాధ్యమైతే హెడర్‌లతో సహా పూర్తి ఇమెయిల్ కంటెంట్‌ను ఇక్కడ అతికించండి...',
    or: 'లేదా',
    uploadFile: 'ఇమెయిల్ ఫైల్‌ను అప్‌లోడ్ చేయండి (.txt, .eml)',
    analyze: 'విశ్లేషించండి',
    analyzing: 'విశ్లేషిస్తోంది...',
    analysisResult: 'విశ్లేషణ ఫలితం',
    verdict: 'తీర్పు',
    reason: 'కారణం',
    history: 'విశ్లేషణ చరిత్ర',
    noHistory: 'ఇంకా విశ్లేషణలు లేవు. పైన ఒక ఇమెయిల్‌ను విశ్లేషించడం ద్వారా ప్రారంభించండి.',
    error: 'లోపం సంభవించింది',
    errorDescription: 'ఇమెయిల్‌ను విశ్లేషించడం సాధ్యం కాలేదు. కంటెంట్ చాలా చిన్నదిగా ఉండవచ్చు లేదా API సేవ ప్రస్తుతం అందుబాటులో లేదు. దయచేసి తర్వాత మళ్లీ ప్రయత్నించండి.',
    fileReadError: 'అప్‌లోడ్ చేసిన ఫైల్‌ను చదవడం విఫలమైంది. దయచేసి ఇది చెల్లుబాటు అయ్యే టెక్స్ట్ ఫైల్ అని నిర్ధారించుకోండి.',
  },
  [Language.ML]: {
    appName: 'ഫിഷ്ഗാർഡ് AI',
    login: 'ലോഗിൻ ചെയ്യുക',
    signup: 'സൈൻ അപ്പ് ചെയ്യുക',
    logout: 'ലോഗ് ഔട്ട്',
    emailAddress: 'ഇമെയിൽ വിലാസം',
    password: 'പാസ്‌വേഡ്',
    confirmPassword: 'പാസ്‌വേഡ് സ്ഥിരീകരിക്കുക',
    dontHaveAccount: 'അക്കൗണ്ട് ഇല്ലേ?',
    alreadyHaveAccount: 'ഇതിനകം അക്കൗണ്ട് ഉണ്ടോ?',
    getStarted: 'തുടങ്ങുക',
    createAccount: 'അക്കൗണ്ട് ഉണ്ടാക്കുക',
    mainHeader: 'ഫിഷിംഗ് ഇമെയിൽ ഡിറ്റക്ടർ',
    mainSubheader: 'AI-യുടെ ശക്തി ഉപയോഗിച്ച് ഭീഷണികൾക്കായി ഇമെയിൽ ഉള്ളടക്കം വിശകലനം ചെയ്യുക.',
    pasteEmail: 'താഴെ ഇമെയിൽ ഉള്ളടക്കം ഒട്ടിക്കുക',
    pastePlaceholder: 'സാധ്യമെങ്കിൽ തലക്കെട്ടുകൾ ഉൾപ്പെടെ മുഴുവൻ ഇമെയിൽ ഉള്ളടക്കവും ഇവിടെ ഒട്ടിക്കുക...',
    or: 'അല്ലെങ്കിൽ',
    uploadFile: 'ഒരു ഇമെയിൽ ഫയൽ അപ്‌ലോഡ് ചെയ്യുക (.txt, .eml)',
    analyze: 'വിശകലനം ചെയ്യുക',
    analyzing: 'വിശകലനം ചെയ്യുന്നു...',
    analysisResult: 'വിശകലന ഫലം',
    verdict: 'വിധി',
    reason: 'കാരണം',
    history: 'വിശകലന ചരിത്രം',
    noHistory: 'ഇതുവരെ വിശകലനങ്ങളൊന്നുമില്ല. മുകളിൽ ഒരു ഇമെയിൽ വിശകലനം ചെയ്തുകൊണ്ട് ആരംഭിക്കുക.',
    error: 'ഒരു പിശക് സംഭവിച്ചു',
    errorDescription: 'ഇമെയിൽ വിശകലനം ചെയ്യാൻ കഴിഞ്ഞില്ല. ഉള്ളടക്കം വളരെ ചെറുതായിരിക്കാം അല്ലെങ്കിൽ API സേവനം നിലവിൽ ലഭ്യമല്ല. ദയവായി പിന്നീട് വീണ്ടും ശ്രമിക്കുക.',
    fileReadError: 'അപ്‌ലോഡ് ചെയ്ത ഫയൽ വായിക്കുന്നതിൽ പരാജയപ്പെട്ടു. അതൊരു സാധുവായ ടെക്സ്റ്റ് ഫയലാണെന്ന് ഉറപ്പാക്കുക.',
  },
  [Language.AR]: {
    appName: 'حارس التصيد AI',
    login: 'تسجيل الدخول',
    signup: 'التسجيل',
    logout: 'تسجيل الخروج',
    emailAddress: 'عنوان البريد الإلكتروني',
    password: 'كلمة المرور',
    confirmPassword: 'تأكيد كلمة المرور',
    dontHaveAccount: 'ليس لديك حساب؟',
    alreadyHaveAccount: 'هل لديك حساب بالفعل؟',
    getStarted: 'البدء',
    createAccount: 'إنشاء حساب',
    mainHeader: 'كاشف رسائل التصيد الاحتيالي',
    mainSubheader: 'حلل محتوى البريد الإلكتروني بحثًا عن التهديدات بقوة الذكاء الاصطناعي.',
    pasteEmail: 'الصق محتوى البريد الإلكتروني أدناه',
    pastePlaceholder: 'الصق محتوى البريد الإلكتروني بالكامل هنا، بما في ذلك الرؤوس إن أمكن...',
    or: 'أو',
    uploadFile: 'تحميل ملف بريد إلكتروني (.txt, .eml)',
    analyze: 'تحليل',
    analyzing: 'جارٍ التحليل...',
    analysisResult: 'نتيجة التحليل',
    verdict: 'الحكم',
    reason: 'السبب',
    history: 'سجل التحليل',
    noHistory: 'لا توجد تحليلات حتى الآن. ابدأ بتحليل بريد إلكتروني أعلاه.',
    error: 'حدث خطأ',
    errorDescription: 'تعذر تحليل البريد الإلكتروني. قد يكون المحتوى قصيرًا جدًا أو أن خدمة الواجهة البرمجية غير متاحة حاليًا. يرجى المحاولة مرة أخرى لاحقًا.',
    fileReadError: 'فشل في قراءة الملف الذي تم تحميله. يرجى التأكد من أنه ملف نصي صالح.',
  },
};
